// Each row is a separate everyday task. The instruction fixes the intended order.
export const routines = [
  ['Lavar as mãos','Molhar as mãos|Ensaboar e enxaguar as mãos|Secar as mãos'],
  ['Servir água','Pegar um copo vazio|Encher o copo com água|Beber a água'],
  ['Vestir a camiseta','Pegar a camiseta|Passar a cabeça pela abertura|Passar os braços pelas mangas'],
  ['Abrir uma carta','Pegar o envelope fechado|Abrir o envelope|Retirar e ler a carta'],
  ['Guardar o livro','Fechar o livro|Levar o livro à estante|Colocar o livro na estante'],
  ['Calçar o sapato','Pegar o sapato|Colocar o pé no sapato|Amarrar o cadarço'],
  ['Comer uma banana','Pegar a banana|Retirar a casca|Comer a fruta'],
  ['Usar a chave','Pegar a chave|Colocar a chave na fechadura|Girar a chave para abrir'],
  ['Acender a luminária','Ligar a luminária na tomada|Apertar o interruptor|Ler com a luz acesa'],
  ['Anotar um recado','Pegar papel e caneta|Escrever o recado|Entregar o recado escrito'],
  ['Regar uma planta','Encher o regador|Levar o regador até a planta|Molhar a terra'],
  ['Cobrir a cama','Esticar o lençol|Colocar o travesseiro sobre o lençol|Colocar a coberta por cima'],
  ['Abrir um aplicativo','Desbloquear a tela|Tocar no ícone do aplicativo|Usar o aplicativo aberto'],
  ['Organizar moedas','Reunir as moedas|Separar por valor|Guardar os grupos separados'],
  ['Lavar uma maçã','Pegar a maçã|Lavar a fruta com água|Secar a fruta limpa'],
  ['Escovar os dentes','Pegar a escova|Colocar pasta na escova|Escovar os dentes|Enxaguar a boca'],
  ['Preparar suco','Pegar o copo|Colocar o suco no copo|Misturar com a colher|Beber o suco'],
  ['Embalar um presente','Colocar o presente no papel|Dobrar o papel sobre o presente|Prender com fita|Entregar o pacote'],
  ['Enviar uma mensagem','Abrir o aplicativo de mensagens|Escolher o contato|Escrever a mensagem|Tocar em enviar'],
  ['Guardar as compras','Trazer as sacolas para a cozinha|Retirar os produtos|Separar os refrigerados|Guardar os refrigerados na geladeira'],
  ['Colocar uma foto no álbum','Abrir o álbum|Escolher uma página vazia|Inserir a foto|Fechar o álbum'],
  ['Fazer uma ligação','Pegar o telefone|Escolher o contato|Iniciar a chamada|Conversar quando a pessoa atender'],
  ['Trocar a fronha','Retirar a fronha usada|Separar a fronha limpa|Colocar o travesseiro na fronha limpa|Devolver o travesseiro à cama'],
  ['Lavar um prato','Retirar restos do prato|Ensaboar o prato|Enxaguar o prato|Colocar no escorredor'],
  ['Montar um quebra-cabeça','Abrir a caixa|Espalhar as peças|Encaixar as peças|Guardar o jogo após terminar'],
  ['Usar o calendário','Abrir o calendário|Localizar o mês|Localizar o dia|Anotar o compromisso nesse dia'],
  ['Varrer o chão','Pegar vassoura e pá|Juntar a sujeira com a vassoura|Recolher a sujeira com a pá|Despejar a sujeira no lixo'],
  ['Preparar a mochila','Abrir a mochila|Colocar o material dentro|Fechar o zíper|Colocar a mochila nas costas'],
  ['Desenhar uma casa','Pegar papel e lápis|Desenhar as paredes|Acrescentar o telhado sobre as paredes|Colorir o desenho'],
  ['Pendurar uma toalha','Pegar a toalha molhada|Estender a toalha no varal|Prender com pregadores|Recolher quando estiver seca'],
  ['Preparar um sanduíche','Lavar as mãos|Separar duas fatias de pão|Colocar o recheio na primeira fatia|Cobrir com a segunda fatia|Servir o sanduíche'],
  ['Plantar uma semente','Pegar um vaso vazio|Colocar terra no vaso|Fazer um pequeno buraco na terra|Colocar e cobrir a semente|Regar a terra'],
  ['Preparar uma salada','Lavar as mãos|Lavar os vegetais|Cortar os vegetais lavados|Colocar os pedaços na tigela|Servir a salada'],
  ['Arrumar a mesa','Limpar a mesa|Colocar a toalha sobre a mesa limpa|Distribuir os pratos nos lugares|Distribuir os talheres nos lugares|Chamar as pessoas para comer'],
  ['Comprar um caderno','Ir à papelaria|Escolher um caderno|Levar o caderno ao caixa|Pagar a compra|Levar o caderno para casa'],
  ['Retirar um livro da biblioteca','Entrar na biblioteca|Procurar o livro desejado|Levar o livro ao balcão|Registrar o empréstimo|Levar o livro emprestado'],
  ['Preparar roupa para guardar','Retirar a roupa seca do varal|Levar a roupa até a mesa|Dobrar a roupa|Abrir a gaveta|Guardar a roupa dobrada'],
  ['Fazer um cartão','Separar papel e lápis|Dobrar o papel ao meio|Escrever a mensagem dentro|Desenhar na capa|Entregar o cartão'],
  ['Organizar fotografias','Reunir as fotos|Separar por ocasião|Escolher uma ordem para cada grupo|Colocar os grupos no álbum|Guardar o álbum'],
  ['Preparar pipoca no aparelho','Pegar o aparelho desligado|Colocar o milho no recipiente indicado|Fechar a tampa|Ligar e aguardar o preparo|Desligar e servir quando estiver pronto'],
  ['Carregar o telefone','Localizar o carregador|Ligar o cabo ao telefone|Ligar o carregador à tomada|Aguardar a carga|Retirar o carregador da tomada'],
  ['Fazer uma lista de compras','Verificar o que falta|Pegar papel e caneta|Anotar os produtos que faltam|Conferir a lista|Levar a lista ao mercado'],
  ['Montar uma pasta','Reunir os documentos|Separar por assunto|Ordenar cada grupo por data|Colocar os grupos na pasta|Identificar a pasta'],
  ['Preparar uma encomenda','Escolher uma caixa|Colocar o objeto na caixa|Proteger o objeto com papel|Fechar a caixa|Escrever o endereço por fora'],
  ['Usar um guarda-chuva','Pegar o guarda-chuva fechado|Ir até a porta|Abrir o guarda-chuva fora da casa|Caminhar protegido da chuva|Fechar ao chegar em local coberto'],
  ['Preparar café coado','Separar o filtro e o suporte|Colocar o filtro no suporte|Colocar café no filtro|Aquecer a água|Despejar a água sobre o café com cuidado|Servir depois de coar'],
  ['Preparar gelatina','Ler as instruções da embalagem|Separar a quantidade indicada de água|Dissolver o pó na água conforme as instruções|Misturar até dissolver|Colocar em um recipiente|Levar à geladeira até firmar'],
  ['Fazer limonada','Lavar os limões|Cortar os limões lavados|Espremer o suco|Colocar o suco na jarra|Adicionar água e misturar|Servir no copo'],
  ['Organizar uma viagem curta','Escolher o destino|Definir as datas|Reservar a passagem|Separar documentos e roupas|Arrumar a mala|Sair para o embarque'],
  ['Ir ao cinema','Escolher o filme|Consultar o horário|Comprar o ingresso|Ir ao cinema no horário|Apresentar o ingresso|Entrar na sala indicada'],
  ['Enviar uma carta pelo correio','Pegar papel e caneta|Escrever a carta|Colocar a carta no envelope|Fechar e endereçar o envelope|Levar ao correio|Pagar a postagem e entregar'],
  ['Fazer uma receita escrita','Escolher a receita|Ler todas as instruções|Separar os ingredientes|Medir as quantidades|Preparar seguindo as etapas|Servir a preparação pronta'],
  ['Participar de uma reunião virtual','Ligar o computador|Conectar à internet|Abrir o convite|Entrar pelo link da reunião|Testar o microfone|Conversar quando for sua vez'],
  ['Organizar uma festa','Definir data e local|Fazer a lista de convidados|Enviar os convites|Preparar o espaço|Receber os convidados|Guardar os materiais após a festa'],
  ['Comprar uma passagem','Escolher o destino|Consultar datas e horários|Escolher o horário|Informar os dados solicitados|Pagar a passagem|Guardar o comprovante'],
  ['Preparar torradas','Pegar as fatias de pão|Colocar na torradeira desligada|Ajustar a intensidade|Ligar a torradeira|Aguardar o término|Retirar e servir as torradas'],
  ['Imprimir um documento','Ligar a impressora|Colocar papel na bandeja|Abrir o documento|Escolher imprimir|Confirmar a impressão|Retirar as folhas impressas'],
  ['Organizar um piquenique','Escolher o local|Conferir a previsão do tempo|Escolher alimentos adequados|Guardar os alimentos em recipientes|Colocar os recipientes na cesta|Levar a cesta ao local'],
  ['Devolver um produto com comprovante','Localizar o comprovante|Conferir as orientações da loja|Separar o produto e acessórios|Embalar os itens|Levar à loja com o comprovante|Solicitar a devolução ao atendente'],
  ['Guardar um jogo de tabuleiro','Encerrar a partida|Reunir as peças|Conferir se todas estão presentes|Dobrar o tabuleiro|Colocar tudo na caixa|Fechar e guardar a caixa']
].map(([title, text]) => ({ title, steps: text.split('|') }));

// Question | correct response | implausible alternatives. No preference is graded.
export const situations = [
  ['Está chovendo e você vai caminhar na rua. O que protege da chuva?','Usar guarda-chuva','Usar uma colher|Pegar um travesseiro|Ler uma revista'],
  ['Você quer beber água. Em qual objeto pode colocá-la?','Copo','Sapato|Livro|Envelope'],
  ['Está frio e você quer aquecer o corpo. O que ajuda?','Vestir um casaco','Abrir a geladeira|Pegar um garfo|Lavar uma janela'],
  ['Suas mãos estão sujas antes de comer. O que fazer?','Lavar as mãos','Guardar o sabonete sem usar|Calçar um sapato|Fechar um livro'],
  ['Você quer ler à noite e o quarto está escuro. O que ajuda?','Acender a luminária','Apagar todas as luzes|Fechar o livro|Cobrir a lâmpada'],
  ['O chão ficou molhado. Como evitar que alguém escorregue?','Secar o chão','Jogar mais água|Espalhar óleo|Cobrir o aviso'],
  ['Você precisa cortar papel. Qual objeto usar?','Tesoura','Copo|Travesseiro|Prato'],
  ['Quer saber as horas. O que consultar?','Relógio','Panela|Toalha|Vaso'],
  ['A planta está com a terra seca. O que fazer?','Regar a terra','Colocar um sapato no vaso|Guardar a planta numa gaveta|Colar papel nas folhas'],
  ['Você terminou de ler o livro da biblioteca. O que fazer no prazo?','Devolver o livro','Esconder o livro|Apagar o título|Retirar as páginas'],
  ['Precisa anotar um telefone. O que ajuda?','Papel e caneta','Garfo e prato|Sabão e toalha|Meia e sapato'],
  ['Quer guardar alimentos que precisam ficar frios. Onde colocar?','Na geladeira','Na estante de livros|No guarda-roupa|Na caixa de ferramentas'],
  ['Sua roupa está molhada depois de lavar. O que ajuda a secar?','Estender no varal','Dobrar e fechar na gaveta|Molhar novamente|Colocar num saco fechado'],
  ['Vai sair e quer trancar a porta. O que precisa?','Chave','Garfo|Caderno|Escova'],
  ['Você quer sentar à mesa. Qual móvel usar?','Cadeira','Janela|Prateleira|Geladeira'],
  ['O telefone está sem carga e você precisa usá-lo. O que fazer?','Conectar ao carregador adequado','Colocar dentro do sapato|Lavar a tela na torneira|Guardar numa panela'],
  ['Você não entendeu um recado. Como esclarecer?','Pedir para explicar novamente','Fingir que entendeu|Apagar o recado antes de ler|Responder outra pergunta'],
  ['Quer chegar à biblioteca e não sabe o caminho. O que ajuda?','Consultar um mapa','Abrir o congelador|Dobrar uma toalha|Contar os talheres'],
  ['Um amigo está falando e você quer ouvir. Qual ação ajuda?','Esperar e prestar atenção','Falar por cima o tempo todo|Cobrir os ouvidos|Aumentar muito a televisão'],
  ['Você quer separar uma data para um compromisso. Onde anotar?','No calendário','Na água do copo|No ar|Na chama do fogão'],
  ['Acabou o papel da impressora. O que colocar nela?','Papel adequado','Tecido molhado|Talheres|Comida'],
  ['Você quer enviar uma carta. Onde escrever o endereço?','No envelope','Dentro do sapato|No prato do almoço|Na roupa do carteiro'],
  ['Você precisa transportar material de estudo. O que usar?','Mochila','Peneira|Xícara|Frigideira'],
  ['Quer varrer o chão. Qual ferramenta usar?','Vassoura','Caneta|Escova de dentes|Colher'],
  ['Está preparando uma salada. O que fazer antes de cortar os vegetais?','Lavar os vegetais','Guardar a faca com os livros|Servir a tigela vazia|Embrulhar tudo em jornal'],
  ['Você terminou uma ligação. Como encerrar a chamada?','Tocar no botão de encerrar','Colocar o telefone na geladeira|Aumentar o volume|Abrir uma janela'],
  ['A lâmpada está apagada e funciona. Como acendê-la?','Acionar o interruptor','Bater no sofá|Girar a maçaneta|Abrir o armário'],
  ['Você vai usar uma receita pela primeira vez. Como começar?','Ler as instruções','Jogar os ingredientes fora|Servir antes de preparar|Rasgar a receita'],
  ['Quer encontrar um livro numa estante organizada por título. O que observar?','O título na lombada','A cor dos seus sapatos|O relógio da cozinha|A temperatura da água'],
  ['Você quer agradecer por uma ajuda. O que dizer?','Obrigado pela ajuda','Que horas fecha a loja?|Onde está a colher?|Quanto pesa a mesa?'],
  ['Um compromisso mudou de horário. Como manter sua agenda correta?','Atualizar o horário anotado','Apagar todos os contatos|Ignorar o novo horário|Anotar uma data aleatória'],
  ['Você esqueceu um item da lista no mercado. Como conferir o que falta?','Reler a lista de compras','Olhar a sola do sapato|Dobrar o comprovante sem ler|Contar as janelas'],
  ['A loja pediu o comprovante para uma troca. O que levar?','O comprovante da compra','Um recibo de outra loja|Um papel em branco|Uma receita culinária'],
  ['Você precisa falar numa reunião. Como pedir a vez?','Sinalizar que deseja falar','Gritar enquanto todos falam|Desligar a reunião de todos|Esconder o microfone'],
  ['Uma caixa será enviada pelo correio. O que ajuda a chegar ao destino?','Identificar o endereço correto','Retirar todas as etiquetas|Escrever um endereço inventado|Deixar sem identificação'],
  ['Você quer evitar esquecer a hora de sair. O que pode configurar?','Um lembrete no horário necessário','Uma foto sem data|Uma lista vazia|O brilho da tela'],
  ['O arquivo ficou difícil de encontrar entre muitos. Como facilitar depois?','Dar um nome descritivo ao arquivo','Dar o mesmo nome a todos|Apagar as pastas|Ocultar o arquivo sem anotar'],
  ['Você quer comparar o preço de dois produtos de mesmo tamanho. O que olhar?','Os preços indicados','A cor do carrinho|O número de portas|A música da loja'],
  ['Vai pegar um ônibus e há várias linhas. O que conferir?','A linha e o destino','A cor do próprio casaco|O peso da mochila|A marca do banco'],
  ['Você combinou devolver um objeto amanhã. Como lembrar?','Anotar um lembrete para amanhã','Anotar para o ano passado|Apagar o combinado|Guardar a agenda sem registrar'],
  ['A pessoa não ouviu sua pergunta. Como ajudar a conversa?','Repetir com clareza','Responder uma coisa sem relação|Ficar de costas e sussurrar|Cobrir a boca e falar mais baixo'],
  ['Você quer guardar documentos de assuntos diferentes. O que facilita encontrar?','Separar em pastas identificadas','Misturar tudo sem ordem|Retirar todos os nomes|Dobrar para esconder os títulos'],
  ['Vai preparar uma receita para duas pessoas em vez de uma. O que consultar?','As quantidades da receita','A cor da embalagem vazia|O título de um romance|O número da sua cadeira'],
  ['Quer evitar perder uma passagem digital. O que fazer?','Salvar o comprovante em local acessível','Apagar a mensagem da passagem|Fechar sem guardar|Trocar o nome por algo sem relação'],
  ['Você chegou ao local de um compromisso. Como avisar a pessoa?','Enviar uma mensagem dizendo que chegou','Perguntar sobre um filme sem contexto|Desligar o telefone|Mandar uma mensagem vazia'],
  ['Um produto da lista está indisponível e você precisa dele. Qual ação esclarece a situação?','Perguntar ao atendente sobre reposição','Procurar dentro do próprio sapato|Apagar o preço de outro produto|Mudar o relógio da loja'],
  ['Você vai viajar e precisa dos documentos no embarque. Como se organizar?','Separá-los em um local acessível','Deixá-los em casa|Escondê-los no fundo de uma caixa fechada|Trocar por folhas vazias'],
  ['Uma reunião virtual começa e seu microfone está desligado. Como falar quando for sua vez?','Ativar o microfone','Fechar a reunião|Desligar o computador|Cobrir a câmera com papel'],
  ['Você recebe duas instruções e esquece a segunda. O que ajuda a realizar a tarefa?','Pedir que repitam a segunda instrução','Inventar uma tarefa sem relação|Ignorar toda a conversa|Apagar a primeira instrução'],
  ['Vai usar um aparelho novo. Como entender os controles?','Ler o manual do aparelho','Testar fios molhados|Forçar as peças fechadas|Ignorar todas as indicações'],
  ['Precisa entregar um documento até sexta-feira. Como planejar?','Anotar o prazo e preparar antes dele','Anotar para a semana seguinte|Esperar o prazo passar|Guardar a informação sem data'],
  ['O mapa mostra duas ruas com nomes parecidos. Como conferir o destino?','Comparar o endereço completo','Escolher pelo primeiro número visto|Ignorar o nome da rua|Seguir um endereço diferente'],
  ['Vai organizar fotos de duas viagens. Como distinguir os grupos?','Separar e identificar cada viagem','Misturar sem identificar|Apagar as datas de todas|Guardar os álbuns vazios'],
  ['Você quer confirmar a reserva de uma passagem. O que verificar?','O comprovante com destino e data','Uma propaganda sem seus dados|Uma foto da mala|O cardápio de ontem'],
  ['Um amigo pediu para chegar às quinze horas. Como registrar sem confundir?','Anotar 15h no dia combinado','Anotar 5h sem dia|Anotar uma data qualquer|Apagar o horário'],
  ['Precisa substituir um ingrediente numa receita por restrição alimentar. Como esclarecer a alternativa?','Consultar uma substituição adequada à receita e à restrição','Ignorar a restrição|Escolher um ingrediente proibido|Retirar o nome da embalagem'],
  ['Uma entrega veio com item diferente do pedido. Como comunicar o problema?','Informar à loja qual item foi pedido e recebido','Dizer apenas uma cor aleatória|Enviar uma mensagem em branco|Apagar o número do pedido'],
  ['Você quer localizar rapidamente um contato no telefone. O que usar?','Buscar pelo nome do contato','Alterar o papel de parede|Fechar todos os aplicativos|Diminuir o brilho'],
  ['Há duas tarefas com prazos diferentes. Qual informação ajuda a escolher a ordem?','Comparar os prazos das tarefas','Comparar a cor das canetas|Contar as cadeiras da sala|Olhar uma foto sem relação'],
  ['Você vai ao cinema com ingresso comprado. O que conferir antes de sair?','Cinema, data e horário do ingresso','O número de colheres na gaveta|A cor da cortina|O tamanho do travesseiro']
].map(([question, answer, others]) => ({ question, answer, distractors: others.split('|') }));

export const sentences = [
  ['Para matar a sede, eu bebo ___.','água'], ['Para descansar à noite, deito na ___.','cama'],
  ['Abro a porta trancada com a ___.','chave'], ['Corto o papel com a ___.','tesoura'],
  ['Leio as histórias escritas no ___.','livro'], ['Sirvo a comida no ___.','prato'],
  ['Calço no pé o ___.','sapato'], ['Sento à mesa em uma ___.','cadeira'],
  ['Vejo as horas no ___.','relógio'], ['Escrevo no papel usando uma ___.','caneta'],
  ['Guardo o leite para ficar frio na ___.','geladeira'], ['Lavo as mãos com água e ___.','sabão'],
  ['Penteio o cabelo com um ___.','pente'], ['Durmo com a cabeça no ___.','travesseiro'],
  ['A chuva molha a ___.','rua'],
  ['Para levar os livros às costas, uso a ___.','mochila'], ['Para varrer o chão, pego a ___.','vassoura'],
  ['Ao cozinhar a sopa, uso uma ___.','panela'], ['Para ver a paisagem de dentro da casa, olho pela ___.','janela'],
  ['Depois de lavar as mãos, seco com a ___.','toalha'], ['Para iluminar o quarto escuro, acendo a ___.','lâmpada'],
  ['Antes de enviar a carta, coloco no ___.','envelope'], ['Para saber a data, consulto o ___.','calendário'],
  ['Quando chove, abro o ___ para me proteger.','guarda-chuva'], ['Na salada, coloquei rodelas de ___.','tomate'],
  ['Para cortar o pão, uso uma ___.','faca'], ['Para prender as folhas, uso um ___.','clipe'],
  ['Na xícara, servi um pouco de ___.','café'], ['Para desenhar e depois apagar, uso um ___.','lápis'],
  ['Para apagar o desenho a lápis, uso a ___.','borracha'],
  ['Ao preparar o sanduíche, coloquei o recheio entre duas fatias de ___.','pão'],
  ['Depois de escolher o filme, comprei o ___ para entrar no cinema.','ingresso'],
  ['Para encontrar o caminho até a biblioteca, consultei um ___.','mapa'],
  ['Antes de guardar a roupa limpa, esperei que ela ficasse ___.','seca'],
  ['A pessoa não ouviu o recado, então precisei ___ a mensagem.','repetir'],
  ['Para organizar os documentos por assunto, usei várias ___.','pastas'],
  ['Ao terminar a chamada, toquei no botão de ___.','encerrar'],
  ['No mercado, consultei a ___ para lembrar os produtos que faltavam.','lista'],
  ['Coloquei terra no vaso antes de plantar a ___.','semente'],
  ['Para servir a limonada, primeiro coloquei a bebida na ___.','jarra'],
  ['Após usar a escova com pasta, enxaguei a ___.','boca'],
  ['Para guardar os talheres organizados, separei garfos e ___.','colheres'],
  ['Ao sair no frio, vesti o casaco para ficar ___.','aquecido'],
  ['Antes de usar o aparelho novo, li o ___.','manual'],
  ['O telefone ficou sem bateria, então liguei ao ___.','carregador'],
  ['Para não esquecer o compromisso marcado para amanhã, configurei um ___ no telefone.','lembrete'],
  ['Depois de colocar o presente na caixa, usei papel para proteger o objeto durante o ___.','transporte'],
  ['Ao escolher uma passagem, conferi a data e o ___ antes de pagar.','destino'],
  ['Durante a reunião virtual, ativei o ___ para que ouvissem minha voz.','microfone'],
  ['Como a receita tinha várias etapas, li todas as ___ antes de começar.','instruções'],
  ['Para reconhecer a pasta de documentos, escrevi seu assunto na ___.','etiqueta'],
  ['Após escrever a carta e fechar o envelope, anotei o ___ do destinatário.','endereço'],
  ['Ao devolver o livro emprestado, levei-o ao balcão da ___.','biblioteca'],
  ['Para aproveitar a luz natural na leitura, abri a cortina da ___.','janela'],
  ['Antes de sair para o cinema, consultei o horário que estava no ___.','ingresso'],
  ['Ao terminar de lavar o prato, coloquei-o no ___ para secar.','escorredor'],
  ['Como a terra estava seca, enchi o regador e reguei a ___.','planta'],
  ['Depois de imprimir o documento, retirei as folhas da ___.','impressora'],
  ['Para conferir a reserva da viagem, abri o ___ recebido após a compra.','comprovante'],
  ['Ao organizar as fotografias, separei um álbum para cada ___.','viagem']
].map(([sentence, answer]) => ({ sentence, answer }));
